### ISSUE TITLE
problems when running code

### ISSUE THREAD

**Issue by WangHan-Chris** [giaylenia/OCTA_segm_study#2]
When I ran the code "OOF/OOF_runme.m", I met a problem as follows:
__________________________________________________
function or variable 'oofseg' is not defined
error OOF_runme (line 76)
    [I_filt, BW]=oofseg(I,range, opts, top_hat);
__________________________________________________
Could you please tell me where I can find this function definition file ? Thanks a lot. My email: 1416006631@qq.com

**Comment by giaylenia** [comment]
Hi, thank you for you comment.

I am using the code kindly shared by Ang Li, author of the paper Ang, L.,Jang, Y., Congwu, D., Yiangtian, P.: Automated segmentation and quantification of OCT angiography for tracking angiogenesis progression. Biomedical Optic Express 8 12, 5604 (2017). Since I am not the author, I can't share the code. Please contact the authors of the articles. 

Let me know then if you have any trouble in running my code or setting the parameters. Notice that each files has some requirements written at the beginning of the script.

Best wishes,
Ylenia

**Comment by WangHan-Chris** [comment]
Dear Ylenia,
Anyway, thank you very much for your reply and your kind reminder.
Best wishes!

**Comment by WangHan-Chris** [comment]
> Hi, thank you for you comment.
> 
> I am using the code kindly shared by Ang Li, author of the paper Ang, L.,Jang, Y., Congwu, D., Yiangtian, P.: Automated segmentation and quantification of OCT angiography for tracking angiogenesis progression. Biomedical Optic Express 8 12, 5604 (2017). Since I am not the author, I can't share the code. Please contact the authors of the articles.
> 
> Let me know then if you have any trouble in running my code or setting the parameters. Notice that each files has some requirements written at the beginning of the script.
> 
> Best wishes,
> Ylenia
————————————————————————————————
Dear Ylenia,
Anyway, thank you very much for your reply and your kind reminder.
Best wishes!

**Comment by WangHan-Chris** [comment]
Dear Ylenia,


Anyway, thank you very much for your reply and your kind reminder.


Best wishes！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "giaylenia/OCTA_segm_study"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [giaylenia/OCTA_segm_study] problems when running code (#2)





 
Hi, thank you for you comment.
 
I am using the code kindly shared by Ang Li, author of the paper Ang, L.,Jang, Y., Congwu, D., Yiangtian, P.: Automated segmentation and quantification of OCT angiography for tracking angiogenesis progression. Biomedical Optic Express 8 12, 5604 (2017). Since I am not the author, I can't share the code. Please contact the authors of the articles.
 
Let me know then if you have any trouble in running my code or setting the parameters. Notice that each files has some requirements written at the beginning of the script.
 
Best wishes,
 Ylenia
